### ISSUE TITLE
Licence : GPLv2 compatibility

### ISSUE THREAD

**Issue by vpicavet** [SAP/odbc-cpp-wrapper#4]
Hello,

This library is licensed as Apache v2. This license is not compatible with GPLv2, making it impossible to link odbc-cpp-wrapper with any software licensed as GPLv2. Note that Apache 2 is compatible with GPLv3.

The problem occurs with this PR for QGIS : https://github.com/qgis/QGIS/pull/30734

QGIS is GPLv2+, the PR adds code and a dependency on odbc-cpp-wrapper, through dynamic linking. This could be ok, under the condition that QGIS with this addition would be distributed as GPLv3. 
But at the same time, it would prevent distributing QGIS with a link to any other library not compatible with GPLv3, which is really annoying.

A solution  would be to add an exception to the Apache 2 licence of this software, so as to make it explicitly compatible with GPLv2.
The subject has already been discussed in various places, and such an exception already proposed : 
- https://blog.gerv.net/2016/09/gplv2-combination-exception-for-the-apache-2-license/
- https://lwn.net/Articles/701155/

Would SAP be ready to add such an exception to the license, so as to ease the integration of this library ?

**Comment by stefanuhrig** [comment]
Thanks for pointing out this licensing issue.

I'll check with our legal department if we can add such an exception. That could take some time though...

**Comment by stefanuhrig** [comment]
I checked with legal and they approved the addition of the exception.

We will add the exception in case our contribution is accepted. The corresponding enhancement proposal is qgis/QGIS-Enhancement-Proposals#151.

**Comment by vpicavet** [comment]
This is good news ! I would suggest to add the exception whatever happens with QGIS QEP 151, as the problem will probably arise with other softwares.

The QEP 151 is not really likely to be merged, mostly because an integration in OGR would be a better solution instead. Same kind of licencing issue will probably arise with such integration though.

**Comment by stefanuhrig** [comment]
GDAL/OGR is licensed under an MIT/X style license, which seems to be compatible with Apache 2. Or do you mean that we need the exception anyway if the GDAL/OGR components including this library were consumed by QGIS or other GPLv2 software?

**Comment by vpicavet** [comment]
The latter indeed. At this point we may enter a grey area, or at least complex situation in the licensing world. Better make the exception anyway and not worry about it !

**Comment by stefanuhrig** [comment]
We added the exception to the license with #5. Thanks for the proposal!
