### ISSUE TITLE
[Windows 10] "HY090 Invalid string or buffer length" error

### ISSUE THREAD

**Issue by slavatrifonov** [SAP/odbc-cpp-wrapper#41]
If i use connection string:
conn->connect("DSN='demo';Driver={SQL Server };SERVER=.\\SQLEXPRESS;Database=DEMO;", NULL, NULL);
i get an error "HY090 Invalid string or buffer length"

What connection string to use without using ODBC Administrator?

Thank you!

**Comment by slavatrifonov** [comment]
using DSN-less connection string
"odbc:DRIVER={SQL Server};SERVER={.\\SQLEXPRESS};DATABASE={DEMO};"
returns same error

**Comment by stefanuhrig** [comment]
You can find the documentation of connection strings for SQL Server at https://learn.microsoft.com/en-us/sql/connect/odbc/dsn-connection-string-attribute?view=sql-server-ver16.

I think there are several issues with your connection string. You must not specify a DSN. The `odbc;` at the start of the second string seems wrong. The driver name must be identical to the driver name in ODBC Administrator. The server part seems wrong to me. Check the documentation.

An example connection string taken from https://learn.microsoft.com/en-us/sql/integration-services/import-export-data/connect-to-an-odbc-data-source-sql-server-import-and-export-wizard?view=sql-server-ver16 looks like that:

```
Driver={ODBC Driver 13 for SQL Server};server=localhost;database=WideWorldImporters;trusted_connection=Yes;
```

**Comment by slavatrifonov** [comment]
Of course I read this documentation. But it didn't help me.
I use only this "Driver={ODBC Driver 13 for SQL Server}" and get same error. 
May be problem is spaces in driver name? 

"server=localhost;database=DEMO;" return Error [IM002] [Microsoft][ODBC Driver Manager] "Data source name not found and no default driver specified"

**Comment by slavatrifonov** [comment]
There are string length limits???
"server=abcdefghijklmnopqrstuvwxyz"  ->  Invalid string or buffer length
"server=abcdefghijklmnopqrstuvwxy"  ->  Data source name not found and no default driver specified

Really?! Only 32 symbols?

**Comment by stefanuhrig** [comment]
Are you using the correct `connect()` overload? You must use the overload taking one argument. The other one is for DSNs.

I had no issues connecting to a local SQL Server instance via

```c++
conn->connect("DRIVER={ODBC Driver 17 for SQL Server};SERVER=localhost;DATABASE=master;Trusted_Connection=yes");
```

**Comment by slavatrifonov** [comment]
omg! i'm stubid and unobservant
of course i use wrong connect() overload!

excuse me! I'ts work. Thank you!
