### ISSUE TITLE
Is this only for SAP HANA or I can connect other databases , too ?

### ISSUE THREAD

**Issue by ffreality** [SAP/odbc-cpp-wrapper#42]
Hi, I would like to use this library to create ODBC plugin for Unreal Engine 5. Is this a specific library to connect SAP HANA resources like link at bellow or I can use it to connect MSSQL, IBM and PostgreSQL and other stuffs.

https://help.sap.com/docs/SAP_HANA_PLATFORM/0eec0d68141541d1b07893a39944924e/66a4169b84b2466892e1af9781049836.html

**Comment by stefanuhrig** [comment]
You can connect to any database that offers an ODBC driver.
