### ISSUE TITLE
where is it include path?

### ISSUE THREAD

**Issue by Sallee1** [SAP/odbc-cpp-wrapper#43]
I did not find the include directory, including project files and generated binaries

**Comment by mrylov** [comment]
Hi @Sallee1,

Please use the instructions given in the [README](https://github.com/SAP/odbc-cpp-wrapper/blob/master/README.md) how to build and install the library. Once all steps are done, you can include the headers, that are normally located in _/usr/local/include/odbc_, as follows:

```
#include <odbc/Connection.h>
#include <odbc/Environment.h>

int main()
{
        odbc::EnvironmentRef env = odbc::Environment::create();

        odbc::ConnectionRef conn = env->createConnection();
        conn->connect("DSN", "user", "pass");
        conn->setAutoCommit(false);
}
```

**Comment by Sallee1** [comment]
What should I do on Windows11 x64?

**Comment by mrylov** [comment]
There are two options for [Windows](https://github.com/SAP/odbc-cpp-wrapper#windows):
Option 1: use [Visual Studio 2015 or later](https://github.com/SAP/odbc-cpp-wrapper#visual-studio-2015-and-later)
Option 2:  use [MSBuild (nmake)](https://github.com/SAP/odbc-cpp-wrapper#msbuild-nmake)

Option 2 will install the library and header files. CMake will install them to C:\Program Files\odbccpp by default. If you prefer a different location, you can set CMake's install prefix to a different path. See https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html for details.

Please read the README carefully.
